# Generated by Django 4.2.4 on 2023-11-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0008_rename_product_photo_product_image"),
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=20, verbose_name="全名")),
                ("zip_code", models.CharField(max_length=10, verbose_name="區碼")),
                ("city", models.CharField(max_length=10, verbose_name="城市")),
                ("county", models.CharField(max_length=50, verbose_name="鄉鎮市")),
                ("phone", models.CharField(max_length=15, verbose_name="電話")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立日期"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日期"),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="付款狀態")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.membermodels",
                        verbose_name="名稱",
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "ordering": ("-create_date",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
    ]
